services:
  docker_registry:
    image: registry:latest
    container_name: docker_registry
    ports:
      - "5000:5000"
    environment:
      -  REGISTRY_HTTP_ADDR=0.0.0.0:5000
    restart:  unless-stopped
